// Generated by CoffeeScript 1.8.0
angular.module('robot', ['ansible']).controller('RobotStatusCtrl', [
  '$scope', '$interval', 'robotInfo', function($scope, $interval, robotInfo) {
    $scope.info = robotInfo();
    return $interval(function() {
      return $scope.info = robotInfo();
    }, 5000);
  }
]);
